- name: loops
  hosts: all
  become: true
  connection : local
  tasks:
    - name: install packages
      ansible.builtin.packages:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - httpd



